insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 독 크런치 밀크 210g', 7200, '간식', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 독 크런치 고구마 210g', 7200, '간식', 0, 'cat.jpg', 3, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '우프니 독 크런치 BBQ', 7200, '간식', 0, 'cat.jpg', 3, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뽀시래기 강아지 치석제거 플라그츄 덴탈껌 관절건강 6개입', 11000, '간식', 0, 'cat.jpg', 3, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뽀시래기 강아지 치석제거 플라그츄 덴탈껌 장건강 6개입', 11000, '간식', 0, 'cat.jpg', 2, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뽀시래기 강아지 치석제거 플라그츄 덴탈껌 눈겅간 6개입', 11000, '간식', 0, 'cat.jpg', 4, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이마시아 소고기 소세지 8p', 1500, '간식', 0, 'cat.jpg', 3, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이마시아 양고기 소세지 8p', 1500, '간식', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이마시아 닭고기 소세지 8p', 1500, '간식', 0, 'cat.jpg', 4, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이마시아 오리고기 소세지 8p', 1500, '간식', 0, 'cat.jpg', 4, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터할리 펫 밀크 바닐라 200ml', 1600, '간식', 0, 'cat.jpg', 3, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터할리 펫 밀크 베이비 200ml', 1600, '간식', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터할리 펫 밀크 어덜트 200ml', 1600, '간식', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터할리 펫 밀크 시니어 200ml', 1600, '간식', 0, 'cat.jpg', 1, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아임펫 리얼 통살의 정석 참치맛 10개입', 5000, '간식', 0, 'cat.jpg', 4, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아임펫 리얼 통살의 정석 황태맛 10개입', 5000, '간식', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아임펫 리얼 통살의 정석 연어맛 10개입', 5000, '간식', 0, 'cat.jpg', 1, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 시금치 120g', 15900, '간식', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 당근 120g', 15900, '간식', 0, 'cat.jpg', 4, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 고구마 120g', 15900, '간식', 0, 'cat.jpg', 4, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 연어껍질 120g', 15900, '간식', 0, 'cat.jpg', 3, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 덕브로콜리 120g', 15900, '간식', 0, 'cat.jpg', 1, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '스위피 오독오독 바삭 치킨블루베리 120g', 15900, '간식', 0, 'cat.jpg', 2, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네츄럴코어 강아지캔 치킨 야채 95g', 1600, '캔', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네츄럴코어 강아지캔 게맛살 치킨 95g', 1600, '캔', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네츄럴코어 강아지캔 치킨 라이스 95g', 1600, '캔', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네츄럴코어 강아지캔 치킨 95g', 1600, '캔', 0, 'cat.jpg', 5, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 소고기 캔 100g', 900, '캔', 0, 'cat.jpg', 4, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 소고기 닭고기 캔 100g', 900, '캔', 0, 'cat.jpg', 2, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 닭고기 캔 100g', 900, '캔', 0, 'cat.jpg', 3, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 소고기 치즈 캔 100g', 900, '캔', 0, 'cat.jpg', 1, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '럭셔리독 양고기 캔 100g', 900, '캔', 0, 'cat.jpg', 2, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 소고기 454g', 49000, '사료', 0, 'cat.jpg', 4, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 사슴고기 454g', 70000, '사료', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 트라이프 양고기 454g', 49000, '사료', 0, 'cat.jpg', 1, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 양고기 454g', 49000, '사료', 0, 'cat.jpg', 1, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 고등어 양고기 454g', 54000, '사료', 0, 'cat.jpg', 1, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '지위픽 독 에어드라이 닭고기 454g', 48000, '사료', 0, 'cat.jpg', 1, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 울트라패드 소형 50매 화이트(40x50cm)', 11000, '위생', 0, 'cat.jpg', 1, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 울트라패드 소형 50매 차콜(40x50cm)', 11000, '위생', 0, 'cat.jpg', 4, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 울트라패드 대형 20매 화이트(60x75cm)', 12000, '위생', 0, 'cat.jpg', 2, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른 울트라패드 대형 20매 차콜(60x75cm)', 12000, '위생', 0, 'cat.jpg', 3, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '멍냥이랑 올인원패드 가성비타입 초대형 80매', 28900, '위생', 0, 'cat.jpg', 2, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '멍냥이랑 올인원패드 가성비타입 대형 160매', 28900, '위생', 0, 'cat.jpg', 3, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '멍냥이랑 올인원패드 가성비타입 중형 200매', 28900, '위생', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '멍냥이랑 올인원패드 가성비타입 소형 400매', 28900, '위생', 0, 'cat.jpg', 5, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '에티펫 치아 깨끗 티슈 30매', 2200, '위생', 0, 'cat.jpg', 4, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '에티펫 눈물자국 깨끗 티슈 30매', 2200, '위생', 0, 'cat.jpg', 2, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바잇미 웁스백 생분해 배변봉투 15매x8롤', 9900, '위생', 0, 'cat.jpg', 5, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '동구밭 반려시선 발비누 시어버터', 13000, '미용', 0, 'cat.jpg', 5, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '도기맨 허니스마일 안면빗', 4900, '미용', 0, 'cat.jpg', 3, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '도기맨 허니스마일 이중참빗', 6200, '미용', 0, 'cat.jpg', 4, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '도기맨 허니스마일 손잡이 참빗 S', 7000, '미용', 0, 'cat.jpg', 4, '강아지', '');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫라움 릴리프 샴푸 500ml', 21900, '미용', 0, 'cat.jpg', 5, '강아지', '');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫라움 퍼리 샴푸 500ml', 20900, '미용', 0, 'cat.jpg', 2, '강아지', '');