insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫띵 공공일스틱 무항생제 닭고기 7개입', 5900, '간식', 0, 'petthing_001_stick_chicken.jpg', 3, '고양이', 'petthing_001_stick_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫띵 공공일스틱 국내산 참치 7개입', 5900, '간식', 0, 'petthing_001_stick_tuna.jpg', 2, '고양이', 'petthing_001_stick_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫띵 공공일스틱 제주 앞바다 고등어 7개입', 5900, '간식', 0, 'petthing_001_stick_mackerel.jpg', 4, '고양이', 'petthing_001_stick_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫띵 공공일스틱 국내산 오리 7개입', 5900, '간식', 0, 'petthing_001_stick_duck.jpg', 4, '고양이', 'petthing_001_stick_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '펫띵 공공일스틱 제주 앞바다 삼치 7개입', 5900, '간식', 0, 'petthing_001_stick_JS_mackerel.jpg', 1, '고양이', 'petthing_001_stick_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이나바 챠오츄르 파우치 참치 연어 14g x 4개', 1780, '간식', 0, 'inaba_ciao_churu_tuna_salmon.jpg', 3, '고양이', 'inaba_ciao_churu_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이나바 챠오츄르 파우치 헤어볼 참치 14g x 4개', 1780, '간식', 0, 'inaba_ciao_churu_tuna.jpg', 5, '고양이', 'inaba_ciao_churu_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이나바 챠오츄르 파우치 닭가슴살 게살 14g X 4개', 1780, '간식', 0, 'inaba_ciao_churu_chicken_crab.jpg', 4, '고양이', 'inaba_ciao_churu_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '이나바 챠오츄르 파우치 가다랑어 14g X 4개', 1780, '간식', 0, 'inaba_ciao_churu_bonito.jpg', 4, '고양이', 'inaba_ciao_churu_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '월간스틱 고양이 츄르 대용량 닭가슴살 연어 30P', 10900, '간식', 0, 'monthstick_chicken_salmon.jpg', 3, '고양이', 'monthstick_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '월간스틱 고양이 츄르 대용량 대구 30P', 10900, '간식', 0, 'monthstick_cod.jpg', 5, '고양이', 'monthstick_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '월간스틱 고양이 츄르 대용량 참치 30P', 10900, '간식', 0, 'monthstick_tuna.jpg', 5, '고양이', 'monthstick_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '월간스틱 고양이 츄르 대용량 닭가슴살 30P', 10900, '간식', 0, 'monthstick_chicken.jpg', 1, '고양이', 'monthstick_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아보덤 캣 그레인프리 참치 게살', 2500, '캔', 0, 'avoderm_tuna_crab.jpg', 5, '고양이', 'avoderm_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아보덤 캣 그레인프리 참치 치킨', 2500, '캔', 0, 'avoderm_tuna_chicken.jpg', 5, '고양이', 'avoderm_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아보덤 캣 그레인프리 참치 새우', 2500, '캔', 0, 'avoderm_tuna_shrimp.jpg', 5, '고양이', 'avoderm_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아보덤 캣 그레인프리 정어리 새우 게살', 2500, '캔', 0, 'avoderm_sardine_shrimp_crab.jpg', 5, '고양이', 'avoderm_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아보덤 캣 그레인프리 연어 치킨', 2500, '캔', 0, 'avoderm_salmon_chicken.jpg', 5, '고양이', 'avoderm_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '아보덤 캣 그레인프리 치킨 오리', 2500, '캔', 0, 'avoderm_chicken_duck.jpg', 5, '고양이', 'avoderm_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뉴트리플랜 흰살참치 닭가슴살', 1500, '캔', 0, 'nutriplan_tuna_chicken.jpg', 5, '고양이', 'nutriplan_tuna_chicken_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뉴트리플랜 흰살참치 게맛살', 1500, '캔', 0, 'nutriplan_tuna_crab.jpg', 3, '고양이', 'nutriplan_tuna_crab_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '뉴트리플랜 흰살참치 멸치', 1500, '캔', 0, 'nutriplan_tuna_anchovy.jpg', 3, '고양이', 'nutriplan_tuna_anchovy_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '황제트릿 동결건조 유산균 간식 닭가슴살 110g', 17000, '간식', 0, 'kingtreat_chicken.jpg', 4, '고양이', 'kingtreat_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '황제트릿 동결건조 유산균 간식 북어 110g', 17000, '간식', 0, 'kingtreat_dried pollack.jpg', 5, '고양이', 'kingtreat_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '황제트릿 동결건조 유산균 간식 연어 110g', 17000, '간식', 0, 'kingtreat_tuna.jpg', 1, '고양이', 'kingtreat_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '황제트릿 동결건조 유산균 간식 가자미 110g', 17000, '간식', 0, 'kingtreat_halibut.jpg', 3, '고양이', 'kingtreat_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '황제트릿 동결건조 유산균 간식 열빙어 110g', 17000, '간식', 0, 'kingtreat_icefish.jpg', 4, '고양이', 'kingtreat_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터펠리스 포캣트릿 열빙어 25g', 9000, '간식', 0, 'doctorfelis_icefish.jpg', 5, '고양이', 'doctorfelis_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터펠리스 포캣트릿 닭가슴살 25g', 9000, '간식', 0, 'doctorfelis_chicken.jpg', 4, '고양이', 'doctorfelis_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터펠리스 포캣트릿 북어 25g', 9000, '간식', 0, 'doctorfelis_driedpollack.jpg', 4, '고양이', 'doctorfelis_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터펠리스 포캣트릿 참치 25g', 9000, '간식', 0, 'doctorfelis_tuna.jpg', 3, '고양이', 'doctorfelis_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터펠리스 포캣트릿 가자미 25g', 9000, '간식', 0, 'doctorfelis_halibut.jpg', 1, '고양이', 'doctorfelis_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '닥터펠리스 포캣트릿 연어 25g', 9000, '간식', 0, 'doctorfelis_salmon.jpg', 2, '고양이', 'doctorfelis_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하림펫푸드 밥이보약 캣 알맞은 체중 3.4kg', 39200, '사료', 0, 'harimpetfood_weight.jpg', 4, '고양이', 'harimpetfood_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하림펫푸드 밥이보약 캣 NO스트레스 3.4kg', 39200, '사료', 0, 'harimpetfood_nostress.jpg', 2, '고양이', 'harimpetfood_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하림펫푸드 밥이보약 캣 걱정없는 헤어볼 3.4kg', 39200, '사료', 0, 'harimpetfood_hairball.jpg', 3, '고양이', 'harimpetfood_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하림펫푸드 밥이보약 캣 활기찬 노후 3.4kg', 39200, '사료', 0, 'harimpetfood_funsenior.jpg', 1, '고양이', 'harimpetfood_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하림펫푸드 밥이보약 캣 탄탄한 성장 3.4kg', 39200, '사료', 0, 'harimpetfood_healthy.jpg', 2, '고양이', 'harimpetfood_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하림펫푸드 밥이보약 캣 빛나는 피모 3.4kg', 39200, '사료', 0, 'harimpetfood_goodhair.jpg', 5, '고양이', 'harimpetfood_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하림펫푸드 더리얼 캣 그레인프리 크런치 시니어 참치 1.6kg', 35000, '사료', 0, 'harimpetfood_grainfree_tuna.jpg', 4, '고양이', 'harimpetfood_grainfree_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하림펫푸드 더리얼 캣 그레인프리 크런치 시니어 닭고기 1.6kg', 35000, '사료', 0, 'harimpetfood_grainfree_chicken.jpg', 5, '고양이', 'harimpetfood_grainfree_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하림펫푸드 더리얼 캣 그레인프리 크런치 시니어 연어 1.6kg', 35000, '사료', 0, 'harimpetfood_grainfree_salmon.jpg', 1, '고양이', 'harimpetfood_grainfree_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른벤토모래 6kg', 13500, '모래', 0, 'bareunmorae.jpg', 5, '고양이', 'bareunmorae_datail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '바른카사모래 라이트 3.8kg', 10900, '모래', 0, 'bareunmorae_light.jpg', 1, '고양이', 'bareunmorae_datail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '더스트몬 카사바플러스 더블밸런스 5L', 66000, '모래', 0, 'dustmon_double_balance.jpg', 1, '고양이', 'dustmon_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '더스트몬 카사바플러스 더블소프트 5L', 69000, '모래', 0, 'dustmon_double_soft.jpg', 4, '고양이', 'dustmon_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '더스트몬 카사바블랜드 밸런스믹스 5L', 51000, '모래', 0, 'dustmon_balance_mix.jpg', 2, '고양이', 'dustmon_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '더스트몬 카사바블랜드 소프트믹스 5L', 54000, '모래', 0, 'dustmon_soft_mix.jpg', 3, '고양이', 'dustmon_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '가필드 고양이모래 그린 가는입자 4.53kg', 35000, '모래', 0, 'garfield_green.jpg', 4, '고양이', 'garfield_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '가필드 고양이모래 보라 굵은입자 4.53kg', 35000, '모래', 0, 'garfield_purple.jpg', 2, '고양이', 'garfield_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '로마샌드 베이직 9kg', 30000, '모래', 0, 'romasand_basic.jpg', 2, '고양이', 'romasand_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '로마샌드 믹스 6kg ', 25000, '모래', 0, 'romasand_mix.jpg', 3, '고양이', 'romasand_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '로마샌드 소프트 6kg', 30000, '모래', 0, 'romasand_fine.jpg', 5, '고양이', 'romasand_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '두잇 푸푸박스 큐브 민트', 49000, '모래', 0, 'duit_toilet_mint.jpg', 5, '고양이', 'duit_toilet_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '두잇 푸푸박스 큐브 화이트', 49000, '모래', 0, 'duit_toilet_white.jpg', 3, '고양이', 'duit_toilet_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '캣처 항균모래삽(굵은 입자용)', 6000, '모래', 0, 'cature_sap_bold.jpg', 3, '고양이', 'cature_sap_detail.jpg');
insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '캣처 항균모래삽(가는 입자용)', 6000, '모래', 0, 'cature_sap_thin.jpg', 4, '고양이', 'cature_sap_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네코이찌 발톱깎이', 18500, '미용', 0, 'necoichi_clawing.jpg', 5, '고양이', 'necoichi_clawing_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '네오짱 꿀벌 원터치 브러쉬 엉킨털 죽은털 제거 빗 옐로우', 7900, '미용', 0, 'neo_brush.jpg', 2, '고양이', 'neo_brush_detail.jpg');

insert into product(product_no, product_name, product_price, product_category, product_qty, product_image, product_star_avg, product_pet_category, product_detail_image) values(product_product_no_SEQ.nextval, '하이포닉 고양이용 샴푸(무향) 300ml', 23000, '미용', 0, 'hyponic_catshampoo.jpg', 3, '고양이', 'hyponic_catshampoo_detail.jpg');
